# usa um tema oficial bonito
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Luiza Cid Ornelas"
description: "Mobility Engineering · Data · Education Impact"
logo: /assets/avatar.jpg        # (opcional) coloque uma foto aqui depois
show_downloads: false
